# Generated by Django 5.2.4 on 2025-07-10 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='examgroup',
            name='name',
            field=models.CharField(default='empty', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examgroup',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.subject'),
            preserve_default=False,
        ),
    ]
