# Generated by Django 5.2.4 on 2025-07-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examgroup_name_examgroup_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examgroup',
            name='subject',
        ),
        migrations.AddField(
            model_name='examgroup',
            name='subject',
            field=models.ManyToManyField(to='exams.subject'),
        ),
    ]
