# Generated by Django 5.2.4 on 2025-07-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_examgroup_subject_examgroup_subject'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examgroup',
            name='student',
        ),
        migrations.AlterField(
            model_name='examgroup',
            name='subject',
            field=models.ManyToManyField(related_name='exam_groups', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='examgroup',
            name='student',
            field=models.ManyToManyField(related_name='exam_groups', to='users.student'),
        ),
    ]
