# Generated by Django 5.2.4 on 2025-07-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_option',
            field=models.CharField(choices=[('a', 'Option A'), ('b', 'Option B'), ('c', 'Option C'), ('d', 'Option D')], default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_option',
            field=models.CharField(blank=True, choices=[('a', 'Option A'), ('b', 'Option B'), ('c', 'Option C'), ('d', 'Option D')], max_length=1, null=True),
        ),
    ]
